version: '3.8'

services:
  client-service:
    build:
      context: ./spring-boot-client-service
    ports:
      - "8086:8086"
    depends_on:
      - postgres
      - kafka

  account-service:
    build:
      context: ./spring-boot-account-service
    ports:
      - "8087:8087"
    depends_on:
      - client-service
      - postgres
      - kafka
      
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spring_boot
    ports:
      - "5433:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper

  consumer:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - kafka
    command: ["kafka-console-consumer", "--topic", "client-topic", "--from-beginning", "--bootstrap-server", "kafka:9092"]